// Generated by CIRCT firtool-1.62.1
module SystolicPE(
  input         clock,
                reset,
                io_en,
                io_clearAcc,
  input  [7:0]  io_aIn,
                io_bIn,
  output [7:0]  io_aOut,
                io_bOut,
  output [31:0] io_acc
);

  reg  [7:0]  aReg;
  reg  [7:0]  bReg;
  reg  [31:0] accReg;
  wire [15:0] prod = {{8{io_aIn[7]}}, io_aIn} * {{8{io_bIn[7]}}, io_bIn};
  wire [31:0] _GEN = {{16{prod[15]}}, prod};
  always @(posedge clock) begin
    if (reset) begin
      aReg <= 8'h0;
      bReg <= 8'h0;
      accReg <= 32'h0;
    end
    else if (io_en) begin
      aReg <= io_aIn;
      bReg <= io_bIn;
      if (io_clearAcc)
        accReg <= _GEN;
      else
        accReg <= accReg + _GEN;
    end
  end // always @(posedge)
  assign io_aOut = aReg;
  assign io_bOut = bReg;
  assign io_acc = accReg;
endmodule

// VCS coverage exclude_file
module mem_16x8(
  input  [3:0] R0_addr,
  input        R0_en,
               R0_clk,
  output [7:0] R0_data,
  input  [3:0] W0_addr,
  input        W0_en,
               W0_clk,
  input  [7:0] W0_data,
  input  [3:0] W1_addr,
  input        W1_en,
               W1_clk,
  input  [7:0] W1_data,
  input  [3:0] W2_addr,
  input        W2_en,
               W2_clk,
  input  [7:0] W2_data,
  input  [3:0] W3_addr,
  input        W3_en,
               W3_clk,
  input  [7:0] W3_data
);

  reg [7:0] Memory[0:15];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
    if (W1_en & 1'h1)
      Memory[W1_addr] <= W1_data;
    if (W2_en & 1'h1)
      Memory[W2_addr] <= W2_data;
    if (W3_en & 1'h1)
      Memory[W3_addr] <= W3_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 8'bx;
endmodule

module mm_accel(
  input          clk,
                 rst,
  input  [31:0]  s_axi_awaddr,
  input          s_axi_awvalid,
  output         s_axi_awready,
  input  [31:0]  s_axi_wdata,
  input  [3:0]   s_axi_wstrb,
  input          s_axi_wvalid,
  output         s_axi_wready,
  output [1:0]   s_axi_bresp,
  output         s_axi_bvalid,
  input          s_axi_bready,
  input  [31:0]  s_axi_araddr,
  input          s_axi_arvalid,
  output         s_axi_arready,
  output [31:0]  s_axi_rdata,
  output [1:0]   s_axi_rresp,
  output         s_axi_rvalid,
  input          s_axi_rready,
  output         mem_req_valid,
                 mem_req_write,
  output [31:0]  mem_req_addr,
  output [127:0] mem_wline,
  input          mem_ready
);

  wire [31:0]  _pes_7_7_io_acc;
  wire [7:0]   _pes_7_6_io_aOut;
  wire [31:0]  _pes_7_6_io_acc;
  wire [7:0]   _pes_7_5_io_aOut;
  wire [31:0]  _pes_7_5_io_acc;
  wire [7:0]   _pes_7_4_io_aOut;
  wire [31:0]  _pes_7_4_io_acc;
  wire [7:0]   _pes_7_3_io_aOut;
  wire [31:0]  _pes_7_3_io_acc;
  wire [7:0]   _pes_7_2_io_aOut;
  wire [31:0]  _pes_7_2_io_acc;
  wire [7:0]   _pes_7_1_io_aOut;
  wire [31:0]  _pes_7_1_io_acc;
  wire [7:0]   _pes_7_0_io_aOut;
  wire [31:0]  _pes_7_0_io_acc;
  wire [7:0]   _pes_6_7_io_bOut;
  wire [31:0]  _pes_6_7_io_acc;
  wire [7:0]   _pes_6_6_io_aOut;
  wire [7:0]   _pes_6_6_io_bOut;
  wire [31:0]  _pes_6_6_io_acc;
  wire [7:0]   _pes_6_5_io_aOut;
  wire [7:0]   _pes_6_5_io_bOut;
  wire [31:0]  _pes_6_5_io_acc;
  wire [7:0]   _pes_6_4_io_aOut;
  wire [7:0]   _pes_6_4_io_bOut;
  wire [31:0]  _pes_6_4_io_acc;
  wire [7:0]   _pes_6_3_io_aOut;
  wire [7:0]   _pes_6_3_io_bOut;
  wire [31:0]  _pes_6_3_io_acc;
  wire [7:0]   _pes_6_2_io_aOut;
  wire [7:0]   _pes_6_2_io_bOut;
  wire [31:0]  _pes_6_2_io_acc;
  wire [7:0]   _pes_6_1_io_aOut;
  wire [7:0]   _pes_6_1_io_bOut;
  wire [31:0]  _pes_6_1_io_acc;
  wire [7:0]   _pes_6_0_io_aOut;
  wire [7:0]   _pes_6_0_io_bOut;
  wire [31:0]  _pes_6_0_io_acc;
  wire [7:0]   _pes_5_7_io_bOut;
  wire [31:0]  _pes_5_7_io_acc;
  wire [7:0]   _pes_5_6_io_aOut;
  wire [7:0]   _pes_5_6_io_bOut;
  wire [31:0]  _pes_5_6_io_acc;
  wire [7:0]   _pes_5_5_io_aOut;
  wire [7:0]   _pes_5_5_io_bOut;
  wire [31:0]  _pes_5_5_io_acc;
  wire [7:0]   _pes_5_4_io_aOut;
  wire [7:0]   _pes_5_4_io_bOut;
  wire [31:0]  _pes_5_4_io_acc;
  wire [7:0]   _pes_5_3_io_aOut;
  wire [7:0]   _pes_5_3_io_bOut;
  wire [31:0]  _pes_5_3_io_acc;
  wire [7:0]   _pes_5_2_io_aOut;
  wire [7:0]   _pes_5_2_io_bOut;
  wire [31:0]  _pes_5_2_io_acc;
  wire [7:0]   _pes_5_1_io_aOut;
  wire [7:0]   _pes_5_1_io_bOut;
  wire [31:0]  _pes_5_1_io_acc;
  wire [7:0]   _pes_5_0_io_aOut;
  wire [7:0]   _pes_5_0_io_bOut;
  wire [31:0]  _pes_5_0_io_acc;
  wire [7:0]   _pes_4_7_io_bOut;
  wire [31:0]  _pes_4_7_io_acc;
  wire [7:0]   _pes_4_6_io_aOut;
  wire [7:0]   _pes_4_6_io_bOut;
  wire [31:0]  _pes_4_6_io_acc;
  wire [7:0]   _pes_4_5_io_aOut;
  wire [7:0]   _pes_4_5_io_bOut;
  wire [31:0]  _pes_4_5_io_acc;
  wire [7:0]   _pes_4_4_io_aOut;
  wire [7:0]   _pes_4_4_io_bOut;
  wire [31:0]  _pes_4_4_io_acc;
  wire [7:0]   _pes_4_3_io_aOut;
  wire [7:0]   _pes_4_3_io_bOut;
  wire [31:0]  _pes_4_3_io_acc;
  wire [7:0]   _pes_4_2_io_aOut;
  wire [7:0]   _pes_4_2_io_bOut;
  wire [31:0]  _pes_4_2_io_acc;
  wire [7:0]   _pes_4_1_io_aOut;
  wire [7:0]   _pes_4_1_io_bOut;
  wire [31:0]  _pes_4_1_io_acc;
  wire [7:0]   _pes_4_0_io_aOut;
  wire [7:0]   _pes_4_0_io_bOut;
  wire [31:0]  _pes_4_0_io_acc;
  wire [7:0]   _pes_3_7_io_bOut;
  wire [31:0]  _pes_3_7_io_acc;
  wire [7:0]   _pes_3_6_io_aOut;
  wire [7:0]   _pes_3_6_io_bOut;
  wire [31:0]  _pes_3_6_io_acc;
  wire [7:0]   _pes_3_5_io_aOut;
  wire [7:0]   _pes_3_5_io_bOut;
  wire [31:0]  _pes_3_5_io_acc;
  wire [7:0]   _pes_3_4_io_aOut;
  wire [7:0]   _pes_3_4_io_bOut;
  wire [31:0]  _pes_3_4_io_acc;
  wire [7:0]   _pes_3_3_io_aOut;
  wire [7:0]   _pes_3_3_io_bOut;
  wire [31:0]  _pes_3_3_io_acc;
  wire [7:0]   _pes_3_2_io_aOut;
  wire [7:0]   _pes_3_2_io_bOut;
  wire [31:0]  _pes_3_2_io_acc;
  wire [7:0]   _pes_3_1_io_aOut;
  wire [7:0]   _pes_3_1_io_bOut;
  wire [31:0]  _pes_3_1_io_acc;
  wire [7:0]   _pes_3_0_io_aOut;
  wire [7:0]   _pes_3_0_io_bOut;
  wire [31:0]  _pes_3_0_io_acc;
  wire [7:0]   _pes_2_7_io_bOut;
  wire [31:0]  _pes_2_7_io_acc;
  wire [7:0]   _pes_2_6_io_aOut;
  wire [7:0]   _pes_2_6_io_bOut;
  wire [31:0]  _pes_2_6_io_acc;
  wire [7:0]   _pes_2_5_io_aOut;
  wire [7:0]   _pes_2_5_io_bOut;
  wire [31:0]  _pes_2_5_io_acc;
  wire [7:0]   _pes_2_4_io_aOut;
  wire [7:0]   _pes_2_4_io_bOut;
  wire [31:0]  _pes_2_4_io_acc;
  wire [7:0]   _pes_2_3_io_aOut;
  wire [7:0]   _pes_2_3_io_bOut;
  wire [31:0]  _pes_2_3_io_acc;
  wire [7:0]   _pes_2_2_io_aOut;
  wire [7:0]   _pes_2_2_io_bOut;
  wire [31:0]  _pes_2_2_io_acc;
  wire [7:0]   _pes_2_1_io_aOut;
  wire [7:0]   _pes_2_1_io_bOut;
  wire [31:0]  _pes_2_1_io_acc;
  wire [7:0]   _pes_2_0_io_aOut;
  wire [7:0]   _pes_2_0_io_bOut;
  wire [31:0]  _pes_2_0_io_acc;
  wire [7:0]   _pes_1_7_io_bOut;
  wire [31:0]  _pes_1_7_io_acc;
  wire [7:0]   _pes_1_6_io_aOut;
  wire [7:0]   _pes_1_6_io_bOut;
  wire [31:0]  _pes_1_6_io_acc;
  wire [7:0]   _pes_1_5_io_aOut;
  wire [7:0]   _pes_1_5_io_bOut;
  wire [31:0]  _pes_1_5_io_acc;
  wire [7:0]   _pes_1_4_io_aOut;
  wire [7:0]   _pes_1_4_io_bOut;
  wire [31:0]  _pes_1_4_io_acc;
  wire [7:0]   _pes_1_3_io_aOut;
  wire [7:0]   _pes_1_3_io_bOut;
  wire [31:0]  _pes_1_3_io_acc;
  wire [7:0]   _pes_1_2_io_aOut;
  wire [7:0]   _pes_1_2_io_bOut;
  wire [31:0]  _pes_1_2_io_acc;
  wire [7:0]   _pes_1_1_io_aOut;
  wire [7:0]   _pes_1_1_io_bOut;
  wire [31:0]  _pes_1_1_io_acc;
  wire [7:0]   _pes_1_0_io_aOut;
  wire [7:0]   _pes_1_0_io_bOut;
  wire [31:0]  _pes_1_0_io_acc;
  wire [7:0]   _pes_0_7_io_bOut;
  wire [31:0]  _pes_0_7_io_acc;
  wire [7:0]   _pes_0_6_io_aOut;
  wire [7:0]   _pes_0_6_io_bOut;
  wire [31:0]  _pes_0_6_io_acc;
  wire [7:0]   _pes_0_5_io_aOut;
  wire [7:0]   _pes_0_5_io_bOut;
  wire [31:0]  _pes_0_5_io_acc;
  wire [7:0]   _pes_0_4_io_aOut;
  wire [7:0]   _pes_0_4_io_bOut;
  wire [31:0]  _pes_0_4_io_acc;
  wire [7:0]   _pes_0_3_io_aOut;
  wire [7:0]   _pes_0_3_io_bOut;
  wire [31:0]  _pes_0_3_io_acc;
  wire [7:0]   _pes_0_2_io_aOut;
  wire [7:0]   _pes_0_2_io_bOut;
  wire [31:0]  _pes_0_2_io_acc;
  wire [7:0]   _pes_0_1_io_aOut;
  wire [7:0]   _pes_0_1_io_bOut;
  wire [31:0]  _pes_0_1_io_acc;
  wire [7:0]   _pes_0_0_io_aOut;
  wire [7:0]   _pes_0_0_io_bOut;
  wire [31:0]  _pes_0_0_io_acc;
  wire [7:0]   _bColBuf_7_ext_R0_data;
  wire [7:0]   _bColBuf_6_ext_R0_data;
  wire [7:0]   _bColBuf_5_ext_R0_data;
  wire [7:0]   _bColBuf_4_ext_R0_data;
  wire [7:0]   _bColBuf_3_ext_R0_data;
  wire [7:0]   _bColBuf_2_ext_R0_data;
  wire [7:0]   _bColBuf_1_ext_R0_data;
  wire [7:0]   _bColBuf_0_ext_R0_data;
  wire [7:0]   _aRowBuf_7_ext_R0_data;
  wire [7:0]   _aRowBuf_6_ext_R0_data;
  wire [7:0]   _aRowBuf_5_ext_R0_data;
  wire [7:0]   _aRowBuf_4_ext_R0_data;
  wire [7:0]   _aRowBuf_3_ext_R0_data;
  wire [7:0]   _aRowBuf_2_ext_R0_data;
  wire [7:0]   _aRowBuf_1_ext_R0_data;
  wire [7:0]   _aRowBuf_0_ext_R0_data;
  reg          busy;
  reg          done;
  reg  [7:0]   kLen;
  reg  [1:0]   loadK;
  reg  [2:0]   loadLane;
  reg  [5:0]   resultIdx;
  reg  [7:0]   t;
  reg  [31:0]  destAddr;
  reg  [31:0]  dmaAddr;
  reg          dmaBusy;
  reg          dmaDone;
  reg  [31:0]  destStride;
  reg  [31:0]  dmaRowBase;
  reg          wState;
  wire         doWrite = s_axi_awvalid & s_axi_wvalid & ~wState;
  reg          awreadyReg;
  reg          wreadyReg;
  reg          bvalidReg;
  reg          rState;
  reg  [5:0]   raddrWord;
  reg          arreadyReg;
  reg          rvalidReg;
  wire         _GEN = raddrWord == 6'h8;
  wire         pushA = doWrite & ~busy & s_axi_awaddr[7:2] == 6'h5;
  wire         pushB = doWrite & ~busy & s_axi_awaddr[7:2] == 6'h6;
  wire         _GEN_0 = doWrite & ~busy;
  wire [3:0]   addr = {loadK, 2'h0};
  wire         _GEN_1 = _GEN_0 & loadLane == 3'h0;
  wire         _GEN_2 = _GEN_1 & pushA;
  wire         _GEN_3 = _GEN_1 & pushB;
  wire [3:0]   addr_1 = {loadK, 2'h1};
  wire [3:0]   addr_2 = {loadK, 2'h2};
  wire [3:0]   addr_3 = {loadK, 2'h3};
  wire [3:0]   addr_4 = {loadK, 2'h0};
  wire         _GEN_4 = _GEN_0 & loadLane == 3'h1;
  wire         _GEN_5 = _GEN_4 & pushA;
  wire         _GEN_6 = _GEN_4 & pushB;
  wire [3:0]   addr_5 = {loadK, 2'h1};
  wire [3:0]   addr_6 = {loadK, 2'h2};
  wire [3:0]   addr_7 = {loadK, 2'h3};
  wire [3:0]   addr_8 = {loadK, 2'h0};
  wire         _GEN_7 = _GEN_0 & loadLane == 3'h2;
  wire         _GEN_8 = _GEN_7 & pushA;
  wire         _GEN_9 = _GEN_7 & pushB;
  wire [3:0]   addr_9 = {loadK, 2'h1};
  wire [3:0]   addr_10 = {loadK, 2'h2};
  wire [3:0]   addr_11 = {loadK, 2'h3};
  wire [3:0]   addr_12 = {loadK, 2'h0};
  wire         _GEN_10 = _GEN_0 & loadLane == 3'h3;
  wire         _GEN_11 = _GEN_10 & pushA;
  wire         _GEN_12 = _GEN_10 & pushB;
  wire [3:0]   addr_13 = {loadK, 2'h1};
  wire [3:0]   addr_14 = {loadK, 2'h2};
  wire [3:0]   addr_15 = {loadK, 2'h3};
  wire [3:0]   addr_16 = {loadK, 2'h0};
  wire         _GEN_13 = _GEN_0 & loadLane == 3'h4;
  wire         _GEN_14 = _GEN_13 & pushA;
  wire         _GEN_15 = _GEN_13 & pushB;
  wire [3:0]   addr_17 = {loadK, 2'h1};
  wire [3:0]   addr_18 = {loadK, 2'h2};
  wire [3:0]   addr_19 = {loadK, 2'h3};
  wire [3:0]   addr_20 = {loadK, 2'h0};
  wire         _GEN_16 = _GEN_0 & loadLane == 3'h5;
  wire         _GEN_17 = _GEN_16 & pushA;
  wire         _GEN_18 = _GEN_16 & pushB;
  wire [3:0]   addr_21 = {loadK, 2'h1};
  wire [3:0]   addr_22 = {loadK, 2'h2};
  wire [3:0]   addr_23 = {loadK, 2'h3};
  wire [3:0]   addr_24 = {loadK, 2'h0};
  wire         _GEN_19 = _GEN_0 & loadLane == 3'h6;
  wire         _GEN_20 = _GEN_19 & pushA;
  wire         _GEN_21 = _GEN_19 & pushB;
  wire [3:0]   addr_25 = {loadK, 2'h1};
  wire [3:0]   addr_26 = {loadK, 2'h2};
  wire [3:0]   addr_27 = {loadK, 2'h3};
  wire [3:0]   addr_28 = {loadK, 2'h0};
  wire         _GEN_22 = _GEN_0 & (&loadLane);
  wire         _GEN_23 = _GEN_22 & pushA;
  wire         _GEN_24 = _GEN_22 & pushB;
  wire [3:0]   addr_29 = {loadK, 2'h1};
  wire [3:0]   addr_30 = {loadK, 2'h2};
  wire [3:0]   addr_31 = {loadK, 2'h3};
  wire [8:0]   _GEN_25 = {1'h0, kLen};
  wire [8:0]   _GEN_26 = {1'h0, t};
  wire         kValid = $signed(_GEN_26) > -9'sh1 & $signed(_GEN_26) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_4 = _GEN_26 - 9'h1;
  wire         kValid_1 =
    $signed(_kIdx_T_4) > -9'sh1 & $signed(_kIdx_T_4) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_7 = _GEN_26 - 9'h2;
  wire         kValid_2 =
    $signed(_kIdx_T_7) > -9'sh1 & $signed(_kIdx_T_7) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_10 = _GEN_26 - 9'h3;
  wire         kValid_3 =
    $signed(_kIdx_T_10) > -9'sh1 & $signed(_kIdx_T_10) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_13 = _GEN_26 - 9'h4;
  wire         kValid_4 =
    $signed(_kIdx_T_13) > -9'sh1 & $signed(_kIdx_T_13) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_16 = _GEN_26 - 9'h5;
  wire         kValid_5 =
    $signed(_kIdx_T_16) > -9'sh1 & $signed(_kIdx_T_16) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_19 = _GEN_26 - 9'h6;
  wire         kValid_6 =
    $signed(_kIdx_T_19) > -9'sh1 & $signed(_kIdx_T_19) < $signed(_GEN_25);
  wire [8:0]   _kIdx_T_22 = _GEN_26 - 9'h7;
  wire         kValid_7 =
    $signed(_kIdx_T_22) > -9'sh1 & $signed(_kIdx_T_22) < $signed(_GEN_25);
  wire         _pes_1_0_io_clearAcc_T = t == 8'h1;
  wire         _pes_2_0_io_clearAcc_T = t == 8'h2;
  wire         _pes_3_0_io_clearAcc_T = t == 8'h3;
  wire         _pes_4_0_io_clearAcc_T = t == 8'h4;
  wire         _pes_5_0_io_clearAcc_T = t == 8'h5;
  wire         _pes_6_0_io_clearAcc_T = t == 8'h6;
  wire         _pes_7_0_io_clearAcc_T = t == 8'h7;
  wire         _pes_7_1_io_clearAcc_T = t == 8'h8;
  wire         _pes_7_2_io_clearAcc_T = t == 8'h9;
  wire         _pes_7_3_io_clearAcc_T = t == 8'hA;
  wire         _pes_7_4_io_clearAcc_T = t == 8'hB;
  wire         _pes_7_5_io_clearAcc_T = t == 8'hC;
  wire         _pes_7_6_io_clearAcc_T = t == 8'hD;
  reg  [3:0]   dmaGrp;
  reg  [127:0] rowLineReg_0;
  reg  [127:0] rowLineReg_1;
  reg  [127:0] rowLineReg_2;
  reg  [127:0] rowLineReg_3;
  reg  [127:0] rowLineReg_4;
  reg  [127:0] rowLineReg_5;
  reg  [127:0] rowLineReg_6;
  reg  [127:0] rowLineReg_7;
  reg  [127:0] casez_tmp;
  always @(*) begin
    casez (dmaGrp[3:1])
      3'b000:
        casez_tmp = rowLineReg_0;
      3'b001:
        casez_tmp = rowLineReg_1;
      3'b010:
        casez_tmp = rowLineReg_2;
      3'b011:
        casez_tmp = rowLineReg_3;
      3'b100:
        casez_tmp = rowLineReg_4;
      3'b101:
        casez_tmp = rowLineReg_5;
      3'b110:
        casez_tmp = rowLineReg_6;
      default:
        casez_tmp = rowLineReg_7;
    endcase
  end // always @(*)
  reg          memReqValid;
  reg          dmaSettle;
  reg  [31:0]  casez_tmp_0;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_0 = _pes_0_0_io_acc;
      3'b001:
        casez_tmp_0 = _pes_0_1_io_acc;
      3'b010:
        casez_tmp_0 = _pes_0_2_io_acc;
      3'b011:
        casez_tmp_0 = _pes_0_3_io_acc;
      3'b100:
        casez_tmp_0 = _pes_0_4_io_acc;
      3'b101:
        casez_tmp_0 = _pes_0_5_io_acc;
      3'b110:
        casez_tmp_0 = _pes_0_6_io_acc;
      default:
        casez_tmp_0 = _pes_0_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_1;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_1 = _pes_1_0_io_acc;
      3'b001:
        casez_tmp_1 = _pes_1_1_io_acc;
      3'b010:
        casez_tmp_1 = _pes_1_2_io_acc;
      3'b011:
        casez_tmp_1 = _pes_1_3_io_acc;
      3'b100:
        casez_tmp_1 = _pes_1_4_io_acc;
      3'b101:
        casez_tmp_1 = _pes_1_5_io_acc;
      3'b110:
        casez_tmp_1 = _pes_1_6_io_acc;
      default:
        casez_tmp_1 = _pes_1_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_2;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_2 = _pes_2_0_io_acc;
      3'b001:
        casez_tmp_2 = _pes_2_1_io_acc;
      3'b010:
        casez_tmp_2 = _pes_2_2_io_acc;
      3'b011:
        casez_tmp_2 = _pes_2_3_io_acc;
      3'b100:
        casez_tmp_2 = _pes_2_4_io_acc;
      3'b101:
        casez_tmp_2 = _pes_2_5_io_acc;
      3'b110:
        casez_tmp_2 = _pes_2_6_io_acc;
      default:
        casez_tmp_2 = _pes_2_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_3;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_3 = _pes_3_0_io_acc;
      3'b001:
        casez_tmp_3 = _pes_3_1_io_acc;
      3'b010:
        casez_tmp_3 = _pes_3_2_io_acc;
      3'b011:
        casez_tmp_3 = _pes_3_3_io_acc;
      3'b100:
        casez_tmp_3 = _pes_3_4_io_acc;
      3'b101:
        casez_tmp_3 = _pes_3_5_io_acc;
      3'b110:
        casez_tmp_3 = _pes_3_6_io_acc;
      default:
        casez_tmp_3 = _pes_3_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_4;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_4 = _pes_4_0_io_acc;
      3'b001:
        casez_tmp_4 = _pes_4_1_io_acc;
      3'b010:
        casez_tmp_4 = _pes_4_2_io_acc;
      3'b011:
        casez_tmp_4 = _pes_4_3_io_acc;
      3'b100:
        casez_tmp_4 = _pes_4_4_io_acc;
      3'b101:
        casez_tmp_4 = _pes_4_5_io_acc;
      3'b110:
        casez_tmp_4 = _pes_4_6_io_acc;
      default:
        casez_tmp_4 = _pes_4_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_5;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_5 = _pes_5_0_io_acc;
      3'b001:
        casez_tmp_5 = _pes_5_1_io_acc;
      3'b010:
        casez_tmp_5 = _pes_5_2_io_acc;
      3'b011:
        casez_tmp_5 = _pes_5_3_io_acc;
      3'b100:
        casez_tmp_5 = _pes_5_4_io_acc;
      3'b101:
        casez_tmp_5 = _pes_5_5_io_acc;
      3'b110:
        casez_tmp_5 = _pes_5_6_io_acc;
      default:
        casez_tmp_5 = _pes_5_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_6;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_6 = _pes_6_0_io_acc;
      3'b001:
        casez_tmp_6 = _pes_6_1_io_acc;
      3'b010:
        casez_tmp_6 = _pes_6_2_io_acc;
      3'b011:
        casez_tmp_6 = _pes_6_3_io_acc;
      3'b100:
        casez_tmp_6 = _pes_6_4_io_acc;
      3'b101:
        casez_tmp_6 = _pes_6_5_io_acc;
      3'b110:
        casez_tmp_6 = _pes_6_6_io_acc;
      default:
        casez_tmp_6 = _pes_6_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  casez_tmp_7;
  always @(*) begin
    casez (resultIdx[2:0])
      3'b000:
        casez_tmp_7 = _pes_7_0_io_acc;
      3'b001:
        casez_tmp_7 = _pes_7_1_io_acc;
      3'b010:
        casez_tmp_7 = _pes_7_2_io_acc;
      3'b011:
        casez_tmp_7 = _pes_7_3_io_acc;
      3'b100:
        casez_tmp_7 = _pes_7_4_io_acc;
      3'b101:
        casez_tmp_7 = _pes_7_5_io_acc;
      3'b110:
        casez_tmp_7 = _pes_7_6_io_acc;
      default:
        casez_tmp_7 = _pes_7_7_io_acc;
    endcase
  end // always @(*)
  reg  [31:0]  rowSelReg_0;
  reg  [31:0]  rowSelReg_1;
  reg  [31:0]  rowSelReg_2;
  reg  [31:0]  rowSelReg_3;
  reg  [31:0]  rowSelReg_4;
  reg  [31:0]  rowSelReg_5;
  reg  [31:0]  rowSelReg_6;
  reg  [31:0]  rowSelReg_7;
  reg  [31:0]  casez_tmp_8;
  always @(*) begin
    casez (resultIdx[5:3])
      3'b000:
        casez_tmp_8 = rowSelReg_0;
      3'b001:
        casez_tmp_8 = rowSelReg_1;
      3'b010:
        casez_tmp_8 = rowSelReg_2;
      3'b011:
        casez_tmp_8 = rowSelReg_3;
      3'b100:
        casez_tmp_8 = rowSelReg_4;
      3'b101:
        casez_tmp_8 = rowSelReg_5;
      3'b110:
        casez_tmp_8 = rowSelReg_6;
      default:
        casez_tmp_8 = rowSelReg_7;
    endcase
  end // always @(*)
  wire         _GEN_27 = s_axi_awaddr[7:2] == 6'h4;
  wire         _GEN_28 = pushA | pushB;
  wire         _GEN_29 = {4'h0, loadK} == kLen[7:2] - 6'h1;
  wire         _GEN_30 = ~dmaBusy | dmaSettle | ~mem_ready | (&dmaGrp);
  wire [31:0]  _dmaRowBase_T = dmaRowBase + (destStride == 32'h0 ? 32'h20 : destStride);
  wire         _GEN_31 = wState & s_axi_bready;
  wire         _GEN_32 = rState & s_axi_rready;
  wire         _dmaStart_T = s_axi_awaddr[7:2] == 6'h0;
  wire         startPulse = doWrite & _dmaStart_T & s_axi_wdata[0] & ~busy;
  wire         softRstPulse = doWrite & _dmaStart_T & s_axi_wdata[1];
  wire         dmaStart = doWrite & _dmaStart_T & s_axi_wdata[2] & ~dmaBusy;
  wire         _GEN_33 = busy & t == kLen + 8'hD;
  wire         _GEN_34 = softRstPulse | startPulse;
  wire         _GEN_35 = mem_ready & (&dmaGrp);
  always @(posedge clk) begin
    if (rst) begin
      busy <= 1'h0;
      done <= 1'h0;
      kLen <= 8'h0;
      loadK <= 2'h0;
      loadLane <= 3'h0;
      resultIdx <= 6'h0;
      t <= 8'h0;
      destAddr <= 32'h0;
      dmaAddr <= 32'h0;
      dmaBusy <= 1'h0;
      dmaDone <= 1'h0;
      destStride <= 32'h0;
      dmaRowBase <= 32'h0;
      wState <= 1'h0;
      awreadyReg <= 1'h0;
      wreadyReg <= 1'h0;
      bvalidReg <= 1'h0;
      rState <= 1'h0;
      raddrWord <= 6'h0;
      arreadyReg <= 1'h0;
      rvalidReg <= 1'h0;
      dmaGrp <= 4'h0;
      memReqValid <= 1'h0;
      dmaSettle <= 1'h0;
    end
    else begin
      busy <= ~softRstPulse & (startPulse | ~_GEN_33 & busy);
      done <= ~_GEN_34 & (_GEN_33 | done);
      if (_GEN_0 & s_axi_awaddr[7:2] == 6'h2)
        kLen <= s_axi_wdata[7:0];
      if (_GEN_0) begin
        if (_GEN_28) begin
          if (_GEN_29)
            loadK <= 2'h0;
          else
            loadK <= loadK + 2'h1;
        end
        else if (_GEN_27)
          loadK <= 2'h0;
        else if (s_axi_awaddr[7:2] == 6'h3)
          loadK <= s_axi_wdata[1:0];
        if (_GEN_28 & _GEN_29)
          loadLane <= loadLane + 3'h1;
        else if (_GEN_27)
          loadLane <= s_axi_wdata[2:0];
      end
      if (_GEN_0 & s_axi_awaddr[7:2] == 6'h7)
        resultIdx <= s_axi_wdata[5:0];
      else if (rState & s_axi_rready & _GEN)
        resultIdx <= resultIdx + 6'h1;
      if (_GEN_34)
        t <= 8'h0;
      else if (busy)
        t <= t + 8'h1;
      if (_GEN_0 & s_axi_awaddr[7:2] == 6'hA)
        destAddr <= s_axi_wdata;
      if (dmaStart) begin
        dmaAddr <= destAddr;
        dmaRowBase <= destAddr;
        dmaGrp <= 4'h0;
      end
      else begin
        if (_GEN_30) begin
        end
        else if (dmaGrp[0])
          dmaAddr <= _dmaRowBase_T;
        else
          dmaAddr <= dmaAddr + 32'h10;
        if (~dmaBusy | dmaSettle | ~mem_ready | (&dmaGrp) | ~(dmaGrp[0])) begin
        end
        else
          dmaRowBase <= _dmaRowBase_T;
        if (_GEN_30) begin
        end
        else
          dmaGrp <= dmaGrp + 4'h1;
      end
      dmaBusy <= dmaStart | (~dmaBusy | dmaSettle | ~_GEN_35) & dmaBusy;
      dmaDone <= ~dmaStart & (dmaBusy & ~dmaSettle & _GEN_35 | dmaDone);
      if (_GEN_0 & s_axi_awaddr[7:2] == 6'hB)
        destStride <= s_axi_wdata;
      if (wState) begin
        wState <= ~_GEN_31 & wState;
        awreadyReg <= ~wState & awreadyReg;
        wreadyReg <= ~wState & wreadyReg;
        bvalidReg <= ~_GEN_31 & bvalidReg;
      end
      else begin
        wState <= doWrite | wState;
        awreadyReg <= doWrite;
        wreadyReg <= doWrite;
        bvalidReg <= doWrite | bvalidReg;
      end
      if (rState)
        rState <= ~_GEN_32 & rState;
      else
        rState <= s_axi_arvalid | rState;
      if (~rState & s_axi_arvalid)
        raddrWord <= s_axi_araddr[7:2];
      if (rState) begin
        arreadyReg <= ~rState & arreadyReg;
        rvalidReg <= ~_GEN_32 & rvalidReg;
      end
      else begin
        arreadyReg <= s_axi_arvalid;
        rvalidReg <= s_axi_arvalid | rvalidReg;
      end
      if (dmaStart | ~dmaBusy) begin
      end
      else
        memReqValid <= dmaSettle | ~mem_ready & memReqValid;
      dmaSettle <=
        dmaStart
        | (dmaBusy ? ~dmaSettle & (mem_ready & ~(&dmaGrp) | dmaSettle) : dmaSettle);
    end
    rowLineReg_0 <=
      dmaGrp[0]
        ? {_pes_0_7_io_acc, _pes_0_6_io_acc, _pes_0_5_io_acc, _pes_0_4_io_acc}
        : {_pes_0_3_io_acc, _pes_0_2_io_acc, _pes_0_1_io_acc, _pes_0_0_io_acc};
    rowLineReg_1 <=
      dmaGrp[0]
        ? {_pes_1_7_io_acc, _pes_1_6_io_acc, _pes_1_5_io_acc, _pes_1_4_io_acc}
        : {_pes_1_3_io_acc, _pes_1_2_io_acc, _pes_1_1_io_acc, _pes_1_0_io_acc};
    rowLineReg_2 <=
      dmaGrp[0]
        ? {_pes_2_7_io_acc, _pes_2_6_io_acc, _pes_2_5_io_acc, _pes_2_4_io_acc}
        : {_pes_2_3_io_acc, _pes_2_2_io_acc, _pes_2_1_io_acc, _pes_2_0_io_acc};
    rowLineReg_3 <=
      dmaGrp[0]
        ? {_pes_3_7_io_acc, _pes_3_6_io_acc, _pes_3_5_io_acc, _pes_3_4_io_acc}
        : {_pes_3_3_io_acc, _pes_3_2_io_acc, _pes_3_1_io_acc, _pes_3_0_io_acc};
    rowLineReg_4 <=
      dmaGrp[0]
        ? {_pes_4_7_io_acc, _pes_4_6_io_acc, _pes_4_5_io_acc, _pes_4_4_io_acc}
        : {_pes_4_3_io_acc, _pes_4_2_io_acc, _pes_4_1_io_acc, _pes_4_0_io_acc};
    rowLineReg_5 <=
      dmaGrp[0]
        ? {_pes_5_7_io_acc, _pes_5_6_io_acc, _pes_5_5_io_acc, _pes_5_4_io_acc}
        : {_pes_5_3_io_acc, _pes_5_2_io_acc, _pes_5_1_io_acc, _pes_5_0_io_acc};
    rowLineReg_6 <=
      dmaGrp[0]
        ? {_pes_6_7_io_acc, _pes_6_6_io_acc, _pes_6_5_io_acc, _pes_6_4_io_acc}
        : {_pes_6_3_io_acc, _pes_6_2_io_acc, _pes_6_1_io_acc, _pes_6_0_io_acc};
    rowLineReg_7 <=
      dmaGrp[0]
        ? {_pes_7_7_io_acc, _pes_7_6_io_acc, _pes_7_5_io_acc, _pes_7_4_io_acc}
        : {_pes_7_3_io_acc, _pes_7_2_io_acc, _pes_7_1_io_acc, _pes_7_0_io_acc};
    rowSelReg_0 <= casez_tmp_0;
    rowSelReg_1 <= casez_tmp_1;
    rowSelReg_2 <= casez_tmp_2;
    rowSelReg_3 <= casez_tmp_3;
    rowSelReg_4 <= casez_tmp_4;
    rowSelReg_5 <= casez_tmp_5;
    rowSelReg_6 <= casez_tmp_6;
    rowSelReg_7 <= casez_tmp_7;
  end // always @(posedge)
  mem_16x8 aRowBuf_0_ext (
    .R0_addr (t[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_0_ext_R0_data),
    .W0_addr (addr_3),
    .W0_en   (_GEN_2),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_2),
    .W1_en   (_GEN_2),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_1),
    .W2_en   (_GEN_2),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr),
    .W3_en   (_GEN_2),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_1_ext (
    .R0_addr (_kIdx_T_4[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_1_ext_R0_data),
    .W0_addr (addr_4),
    .W0_en   (_GEN_5),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[7:0]),
    .W1_addr (addr_7),
    .W1_en   (_GEN_5),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[31:24]),
    .W2_addr (addr_6),
    .W2_en   (_GEN_5),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[23:16]),
    .W3_addr (addr_5),
    .W3_en   (_GEN_5),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[15:8])
  );
  mem_16x8 aRowBuf_2_ext (
    .R0_addr (_kIdx_T_7[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_2_ext_R0_data),
    .W0_addr (addr_11),
    .W0_en   (_GEN_8),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_10),
    .W1_en   (_GEN_8),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_9),
    .W2_en   (_GEN_8),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_8),
    .W3_en   (_GEN_8),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_3_ext (
    .R0_addr (_kIdx_T_10[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_3_ext_R0_data),
    .W0_addr (addr_15),
    .W0_en   (_GEN_11),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_14),
    .W1_en   (_GEN_11),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_13),
    .W2_en   (_GEN_11),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_12),
    .W3_en   (_GEN_11),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_4_ext (
    .R0_addr (_kIdx_T_13[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_4_ext_R0_data),
    .W0_addr (addr_19),
    .W0_en   (_GEN_14),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_18),
    .W1_en   (_GEN_14),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_17),
    .W2_en   (_GEN_14),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_16),
    .W3_en   (_GEN_14),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_5_ext (
    .R0_addr (_kIdx_T_16[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_5_ext_R0_data),
    .W0_addr (addr_23),
    .W0_en   (_GEN_17),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_22),
    .W1_en   (_GEN_17),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_21),
    .W2_en   (_GEN_17),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_20),
    .W3_en   (_GEN_17),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_6_ext (
    .R0_addr (_kIdx_T_19[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_6_ext_R0_data),
    .W0_addr (addr_27),
    .W0_en   (_GEN_20),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_26),
    .W1_en   (_GEN_20),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_25),
    .W2_en   (_GEN_20),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_24),
    .W3_en   (_GEN_20),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 aRowBuf_7_ext (
    .R0_addr (_kIdx_T_22[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_aRowBuf_7_ext_R0_data),
    .W0_addr (addr_31),
    .W0_en   (_GEN_23),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_30),
    .W1_en   (_GEN_23),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_29),
    .W2_en   (_GEN_23),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_28),
    .W3_en   (_GEN_23),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_0_ext (
    .R0_addr (t[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_0_ext_R0_data),
    .W0_addr (addr_3),
    .W0_en   (_GEN_3),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_2),
    .W1_en   (_GEN_3),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_1),
    .W2_en   (_GEN_3),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr),
    .W3_en   (_GEN_3),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_1_ext (
    .R0_addr (_kIdx_T_4[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_1_ext_R0_data),
    .W0_addr (addr_4),
    .W0_en   (_GEN_6),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[7:0]),
    .W1_addr (addr_7),
    .W1_en   (_GEN_6),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[31:24]),
    .W2_addr (addr_6),
    .W2_en   (_GEN_6),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[23:16]),
    .W3_addr (addr_5),
    .W3_en   (_GEN_6),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[15:8])
  );
  mem_16x8 bColBuf_2_ext (
    .R0_addr (_kIdx_T_7[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_2_ext_R0_data),
    .W0_addr (addr_11),
    .W0_en   (_GEN_9),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_10),
    .W1_en   (_GEN_9),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_9),
    .W2_en   (_GEN_9),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_8),
    .W3_en   (_GEN_9),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_3_ext (
    .R0_addr (_kIdx_T_10[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_3_ext_R0_data),
    .W0_addr (addr_15),
    .W0_en   (_GEN_12),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_14),
    .W1_en   (_GEN_12),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_13),
    .W2_en   (_GEN_12),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_12),
    .W3_en   (_GEN_12),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_4_ext (
    .R0_addr (_kIdx_T_13[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_4_ext_R0_data),
    .W0_addr (addr_19),
    .W0_en   (_GEN_15),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_18),
    .W1_en   (_GEN_15),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_17),
    .W2_en   (_GEN_15),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_16),
    .W3_en   (_GEN_15),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_5_ext (
    .R0_addr (_kIdx_T_16[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_5_ext_R0_data),
    .W0_addr (addr_23),
    .W0_en   (_GEN_18),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_22),
    .W1_en   (_GEN_18),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_21),
    .W2_en   (_GEN_18),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_20),
    .W3_en   (_GEN_18),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_6_ext (
    .R0_addr (_kIdx_T_19[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_6_ext_R0_data),
    .W0_addr (addr_27),
    .W0_en   (_GEN_21),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_26),
    .W1_en   (_GEN_21),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_25),
    .W2_en   (_GEN_21),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_24),
    .W3_en   (_GEN_21),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  mem_16x8 bColBuf_7_ext (
    .R0_addr (_kIdx_T_22[3:0]),
    .R0_en   (1'h1),
    .R0_clk  (clk),
    .R0_data (_bColBuf_7_ext_R0_data),
    .W0_addr (addr_31),
    .W0_en   (_GEN_24),
    .W0_clk  (clk),
    .W0_data (s_axi_wdata[31:24]),
    .W1_addr (addr_30),
    .W1_en   (_GEN_24),
    .W1_clk  (clk),
    .W1_data (s_axi_wdata[23:16]),
    .W2_addr (addr_29),
    .W2_en   (_GEN_24),
    .W2_clk  (clk),
    .W2_data (s_axi_wdata[15:8]),
    .W3_addr (addr_28),
    .W3_en   (_GEN_24),
    .W3_clk  (clk),
    .W3_data (s_axi_wdata[7:0])
  );
  SystolicPE pes_0_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (t == 8'h0),
    .io_aIn      (kValid ? _aRowBuf_0_ext_R0_data : 8'h0),
    .io_bIn      (kValid ? _bColBuf_0_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_0_io_aOut),
    .io_bOut     (_pes_0_0_io_bOut),
    .io_acc      (_pes_0_0_io_acc)
  );
  SystolicPE pes_0_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_1_0_io_clearAcc_T),
    .io_aIn      (_pes_0_0_io_aOut),
    .io_bIn      (kValid_1 ? _bColBuf_1_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_1_io_aOut),
    .io_bOut     (_pes_0_1_io_bOut),
    .io_acc      (_pes_0_1_io_acc)
  );
  SystolicPE pes_0_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_2_0_io_clearAcc_T),
    .io_aIn      (_pes_0_1_io_aOut),
    .io_bIn      (kValid_2 ? _bColBuf_2_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_2_io_aOut),
    .io_bOut     (_pes_0_2_io_bOut),
    .io_acc      (_pes_0_2_io_acc)
  );
  SystolicPE pes_0_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_3_0_io_clearAcc_T),
    .io_aIn      (_pes_0_2_io_aOut),
    .io_bIn      (kValid_3 ? _bColBuf_3_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_3_io_aOut),
    .io_bOut     (_pes_0_3_io_bOut),
    .io_acc      (_pes_0_3_io_acc)
  );
  SystolicPE pes_0_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_4_0_io_clearAcc_T),
    .io_aIn      (_pes_0_3_io_aOut),
    .io_bIn      (kValid_4 ? _bColBuf_4_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_4_io_aOut),
    .io_bOut     (_pes_0_4_io_bOut),
    .io_acc      (_pes_0_4_io_acc)
  );
  SystolicPE pes_0_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (_pes_0_4_io_aOut),
    .io_bIn      (kValid_5 ? _bColBuf_5_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_5_io_aOut),
    .io_bOut     (_pes_0_5_io_bOut),
    .io_acc      (_pes_0_5_io_acc)
  );
  SystolicPE pes_0_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_0_5_io_aOut),
    .io_bIn      (kValid_6 ? _bColBuf_6_ext_R0_data : 8'h0),
    .io_aOut     (_pes_0_6_io_aOut),
    .io_bOut     (_pes_0_6_io_bOut),
    .io_acc      (_pes_0_6_io_acc)
  );
  SystolicPE pes_0_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_0_6_io_aOut),
    .io_bIn      (kValid_7 ? _bColBuf_7_ext_R0_data : 8'h0),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_0_7_io_bOut),
    .io_acc      (_pes_0_7_io_acc)
  );
  SystolicPE pes_1_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_1_0_io_clearAcc_T),
    .io_aIn      (kValid_1 ? _aRowBuf_1_ext_R0_data : 8'h0),
    .io_bIn      (_pes_0_0_io_bOut),
    .io_aOut     (_pes_1_0_io_aOut),
    .io_bOut     (_pes_1_0_io_bOut),
    .io_acc      (_pes_1_0_io_acc)
  );
  SystolicPE pes_1_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_2_0_io_clearAcc_T),
    .io_aIn      (_pes_1_0_io_aOut),
    .io_bIn      (_pes_0_1_io_bOut),
    .io_aOut     (_pes_1_1_io_aOut),
    .io_bOut     (_pes_1_1_io_bOut),
    .io_acc      (_pes_1_1_io_acc)
  );
  SystolicPE pes_1_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_3_0_io_clearAcc_T),
    .io_aIn      (_pes_1_1_io_aOut),
    .io_bIn      (_pes_0_2_io_bOut),
    .io_aOut     (_pes_1_2_io_aOut),
    .io_bOut     (_pes_1_2_io_bOut),
    .io_acc      (_pes_1_2_io_acc)
  );
  SystolicPE pes_1_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_4_0_io_clearAcc_T),
    .io_aIn      (_pes_1_2_io_aOut),
    .io_bIn      (_pes_0_3_io_bOut),
    .io_aOut     (_pes_1_3_io_aOut),
    .io_bOut     (_pes_1_3_io_bOut),
    .io_acc      (_pes_1_3_io_acc)
  );
  SystolicPE pes_1_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (_pes_1_3_io_aOut),
    .io_bIn      (_pes_0_4_io_bOut),
    .io_aOut     (_pes_1_4_io_aOut),
    .io_bOut     (_pes_1_4_io_bOut),
    .io_acc      (_pes_1_4_io_acc)
  );
  SystolicPE pes_1_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_1_4_io_aOut),
    .io_bIn      (_pes_0_5_io_bOut),
    .io_aOut     (_pes_1_5_io_aOut),
    .io_bOut     (_pes_1_5_io_bOut),
    .io_acc      (_pes_1_5_io_acc)
  );
  SystolicPE pes_1_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_1_5_io_aOut),
    .io_bIn      (_pes_0_6_io_bOut),
    .io_aOut     (_pes_1_6_io_aOut),
    .io_bOut     (_pes_1_6_io_bOut),
    .io_acc      (_pes_1_6_io_acc)
  );
  SystolicPE pes_1_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_1_6_io_aOut),
    .io_bIn      (_pes_0_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_1_7_io_bOut),
    .io_acc      (_pes_1_7_io_acc)
  );
  SystolicPE pes_2_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_2_0_io_clearAcc_T),
    .io_aIn      (kValid_2 ? _aRowBuf_2_ext_R0_data : 8'h0),
    .io_bIn      (_pes_1_0_io_bOut),
    .io_aOut     (_pes_2_0_io_aOut),
    .io_bOut     (_pes_2_0_io_bOut),
    .io_acc      (_pes_2_0_io_acc)
  );
  SystolicPE pes_2_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_3_0_io_clearAcc_T),
    .io_aIn      (_pes_2_0_io_aOut),
    .io_bIn      (_pes_1_1_io_bOut),
    .io_aOut     (_pes_2_1_io_aOut),
    .io_bOut     (_pes_2_1_io_bOut),
    .io_acc      (_pes_2_1_io_acc)
  );
  SystolicPE pes_2_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_4_0_io_clearAcc_T),
    .io_aIn      (_pes_2_1_io_aOut),
    .io_bIn      (_pes_1_2_io_bOut),
    .io_aOut     (_pes_2_2_io_aOut),
    .io_bOut     (_pes_2_2_io_bOut),
    .io_acc      (_pes_2_2_io_acc)
  );
  SystolicPE pes_2_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (_pes_2_2_io_aOut),
    .io_bIn      (_pes_1_3_io_bOut),
    .io_aOut     (_pes_2_3_io_aOut),
    .io_bOut     (_pes_2_3_io_bOut),
    .io_acc      (_pes_2_3_io_acc)
  );
  SystolicPE pes_2_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_2_3_io_aOut),
    .io_bIn      (_pes_1_4_io_bOut),
    .io_aOut     (_pes_2_4_io_aOut),
    .io_bOut     (_pes_2_4_io_bOut),
    .io_acc      (_pes_2_4_io_acc)
  );
  SystolicPE pes_2_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_2_4_io_aOut),
    .io_bIn      (_pes_1_5_io_bOut),
    .io_aOut     (_pes_2_5_io_aOut),
    .io_bOut     (_pes_2_5_io_bOut),
    .io_acc      (_pes_2_5_io_acc)
  );
  SystolicPE pes_2_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_2_5_io_aOut),
    .io_bIn      (_pes_1_6_io_bOut),
    .io_aOut     (_pes_2_6_io_aOut),
    .io_bOut     (_pes_2_6_io_bOut),
    .io_acc      (_pes_2_6_io_acc)
  );
  SystolicPE pes_2_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_2_6_io_aOut),
    .io_bIn      (_pes_1_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_2_7_io_bOut),
    .io_acc      (_pes_2_7_io_acc)
  );
  SystolicPE pes_3_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_3_0_io_clearAcc_T),
    .io_aIn      (kValid_3 ? _aRowBuf_3_ext_R0_data : 8'h0),
    .io_bIn      (_pes_2_0_io_bOut),
    .io_aOut     (_pes_3_0_io_aOut),
    .io_bOut     (_pes_3_0_io_bOut),
    .io_acc      (_pes_3_0_io_acc)
  );
  SystolicPE pes_3_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_4_0_io_clearAcc_T),
    .io_aIn      (_pes_3_0_io_aOut),
    .io_bIn      (_pes_2_1_io_bOut),
    .io_aOut     (_pes_3_1_io_aOut),
    .io_bOut     (_pes_3_1_io_bOut),
    .io_acc      (_pes_3_1_io_acc)
  );
  SystolicPE pes_3_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (_pes_3_1_io_aOut),
    .io_bIn      (_pes_2_2_io_bOut),
    .io_aOut     (_pes_3_2_io_aOut),
    .io_bOut     (_pes_3_2_io_bOut),
    .io_acc      (_pes_3_2_io_acc)
  );
  SystolicPE pes_3_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_3_2_io_aOut),
    .io_bIn      (_pes_2_3_io_bOut),
    .io_aOut     (_pes_3_3_io_aOut),
    .io_bOut     (_pes_3_3_io_bOut),
    .io_acc      (_pes_3_3_io_acc)
  );
  SystolicPE pes_3_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_3_3_io_aOut),
    .io_bIn      (_pes_2_4_io_bOut),
    .io_aOut     (_pes_3_4_io_aOut),
    .io_bOut     (_pes_3_4_io_bOut),
    .io_acc      (_pes_3_4_io_acc)
  );
  SystolicPE pes_3_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_3_4_io_aOut),
    .io_bIn      (_pes_2_5_io_bOut),
    .io_aOut     (_pes_3_5_io_aOut),
    .io_bOut     (_pes_3_5_io_bOut),
    .io_acc      (_pes_3_5_io_acc)
  );
  SystolicPE pes_3_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_3_5_io_aOut),
    .io_bIn      (_pes_2_6_io_bOut),
    .io_aOut     (_pes_3_6_io_aOut),
    .io_bOut     (_pes_3_6_io_bOut),
    .io_acc      (_pes_3_6_io_acc)
  );
  SystolicPE pes_3_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_3_io_clearAcc_T),
    .io_aIn      (_pes_3_6_io_aOut),
    .io_bIn      (_pes_2_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_3_7_io_bOut),
    .io_acc      (_pes_3_7_io_acc)
  );
  SystolicPE pes_4_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_4_0_io_clearAcc_T),
    .io_aIn      (kValid_4 ? _aRowBuf_4_ext_R0_data : 8'h0),
    .io_bIn      (_pes_3_0_io_bOut),
    .io_aOut     (_pes_4_0_io_aOut),
    .io_bOut     (_pes_4_0_io_bOut),
    .io_acc      (_pes_4_0_io_acc)
  );
  SystolicPE pes_4_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (_pes_4_0_io_aOut),
    .io_bIn      (_pes_3_1_io_bOut),
    .io_aOut     (_pes_4_1_io_aOut),
    .io_bOut     (_pes_4_1_io_bOut),
    .io_acc      (_pes_4_1_io_acc)
  );
  SystolicPE pes_4_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_4_1_io_aOut),
    .io_bIn      (_pes_3_2_io_bOut),
    .io_aOut     (_pes_4_2_io_aOut),
    .io_bOut     (_pes_4_2_io_bOut),
    .io_acc      (_pes_4_2_io_acc)
  );
  SystolicPE pes_4_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_4_2_io_aOut),
    .io_bIn      (_pes_3_3_io_bOut),
    .io_aOut     (_pes_4_3_io_aOut),
    .io_bOut     (_pes_4_3_io_bOut),
    .io_acc      (_pes_4_3_io_acc)
  );
  SystolicPE pes_4_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_4_3_io_aOut),
    .io_bIn      (_pes_3_4_io_bOut),
    .io_aOut     (_pes_4_4_io_aOut),
    .io_bOut     (_pes_4_4_io_bOut),
    .io_acc      (_pes_4_4_io_acc)
  );
  SystolicPE pes_4_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_4_4_io_aOut),
    .io_bIn      (_pes_3_5_io_bOut),
    .io_aOut     (_pes_4_5_io_aOut),
    .io_bOut     (_pes_4_5_io_bOut),
    .io_acc      (_pes_4_5_io_acc)
  );
  SystolicPE pes_4_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_3_io_clearAcc_T),
    .io_aIn      (_pes_4_5_io_aOut),
    .io_bIn      (_pes_3_6_io_bOut),
    .io_aOut     (_pes_4_6_io_aOut),
    .io_bOut     (_pes_4_6_io_bOut),
    .io_acc      (_pes_4_6_io_acc)
  );
  SystolicPE pes_4_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_4_io_clearAcc_T),
    .io_aIn      (_pes_4_6_io_aOut),
    .io_bIn      (_pes_3_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_4_7_io_bOut),
    .io_acc      (_pes_4_7_io_acc)
  );
  SystolicPE pes_5_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_5_0_io_clearAcc_T),
    .io_aIn      (kValid_5 ? _aRowBuf_5_ext_R0_data : 8'h0),
    .io_bIn      (_pes_4_0_io_bOut),
    .io_aOut     (_pes_5_0_io_aOut),
    .io_bOut     (_pes_5_0_io_bOut),
    .io_acc      (_pes_5_0_io_acc)
  );
  SystolicPE pes_5_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (_pes_5_0_io_aOut),
    .io_bIn      (_pes_4_1_io_bOut),
    .io_aOut     (_pes_5_1_io_aOut),
    .io_bOut     (_pes_5_1_io_bOut),
    .io_acc      (_pes_5_1_io_acc)
  );
  SystolicPE pes_5_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_5_1_io_aOut),
    .io_bIn      (_pes_4_2_io_bOut),
    .io_aOut     (_pes_5_2_io_aOut),
    .io_bOut     (_pes_5_2_io_bOut),
    .io_acc      (_pes_5_2_io_acc)
  );
  SystolicPE pes_5_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_5_2_io_aOut),
    .io_bIn      (_pes_4_3_io_bOut),
    .io_aOut     (_pes_5_3_io_aOut),
    .io_bOut     (_pes_5_3_io_bOut),
    .io_acc      (_pes_5_3_io_acc)
  );
  SystolicPE pes_5_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_5_3_io_aOut),
    .io_bIn      (_pes_4_4_io_bOut),
    .io_aOut     (_pes_5_4_io_aOut),
    .io_bOut     (_pes_5_4_io_bOut),
    .io_acc      (_pes_5_4_io_acc)
  );
  SystolicPE pes_5_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_3_io_clearAcc_T),
    .io_aIn      (_pes_5_4_io_aOut),
    .io_bIn      (_pes_4_5_io_bOut),
    .io_aOut     (_pes_5_5_io_aOut),
    .io_bOut     (_pes_5_5_io_bOut),
    .io_acc      (_pes_5_5_io_acc)
  );
  SystolicPE pes_5_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_4_io_clearAcc_T),
    .io_aIn      (_pes_5_5_io_aOut),
    .io_bIn      (_pes_4_6_io_bOut),
    .io_aOut     (_pes_5_6_io_aOut),
    .io_bOut     (_pes_5_6_io_bOut),
    .io_acc      (_pes_5_6_io_acc)
  );
  SystolicPE pes_5_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_5_io_clearAcc_T),
    .io_aIn      (_pes_5_6_io_aOut),
    .io_bIn      (_pes_4_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_5_7_io_bOut),
    .io_acc      (_pes_5_7_io_acc)
  );
  SystolicPE pes_6_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_6_0_io_clearAcc_T),
    .io_aIn      (kValid_6 ? _aRowBuf_6_ext_R0_data : 8'h0),
    .io_bIn      (_pes_5_0_io_bOut),
    .io_aOut     (_pes_6_0_io_aOut),
    .io_bOut     (_pes_6_0_io_bOut),
    .io_acc      (_pes_6_0_io_acc)
  );
  SystolicPE pes_6_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (_pes_6_0_io_aOut),
    .io_bIn      (_pes_5_1_io_bOut),
    .io_aOut     (_pes_6_1_io_aOut),
    .io_bOut     (_pes_6_1_io_bOut),
    .io_acc      (_pes_6_1_io_acc)
  );
  SystolicPE pes_6_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_6_1_io_aOut),
    .io_bIn      (_pes_5_2_io_bOut),
    .io_aOut     (_pes_6_2_io_aOut),
    .io_bOut     (_pes_6_2_io_bOut),
    .io_acc      (_pes_6_2_io_acc)
  );
  SystolicPE pes_6_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_6_2_io_aOut),
    .io_bIn      (_pes_5_3_io_bOut),
    .io_aOut     (_pes_6_3_io_aOut),
    .io_bOut     (_pes_6_3_io_bOut),
    .io_acc      (_pes_6_3_io_acc)
  );
  SystolicPE pes_6_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_3_io_clearAcc_T),
    .io_aIn      (_pes_6_3_io_aOut),
    .io_bIn      (_pes_5_4_io_bOut),
    .io_aOut     (_pes_6_4_io_aOut),
    .io_bOut     (_pes_6_4_io_bOut),
    .io_acc      (_pes_6_4_io_acc)
  );
  SystolicPE pes_6_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_4_io_clearAcc_T),
    .io_aIn      (_pes_6_4_io_aOut),
    .io_bIn      (_pes_5_5_io_bOut),
    .io_aOut     (_pes_6_5_io_aOut),
    .io_bOut     (_pes_6_5_io_bOut),
    .io_acc      (_pes_6_5_io_acc)
  );
  SystolicPE pes_6_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_5_io_clearAcc_T),
    .io_aIn      (_pes_6_5_io_aOut),
    .io_bIn      (_pes_5_6_io_bOut),
    .io_aOut     (_pes_6_6_io_aOut),
    .io_bOut     (_pes_6_6_io_bOut),
    .io_acc      (_pes_6_6_io_acc)
  );
  SystolicPE pes_6_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_6_io_clearAcc_T),
    .io_aIn      (_pes_6_6_io_aOut),
    .io_bIn      (_pes_5_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (_pes_6_7_io_bOut),
    .io_acc      (_pes_6_7_io_acc)
  );
  SystolicPE pes_7_0 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_0_io_clearAcc_T),
    .io_aIn      (kValid_7 ? _aRowBuf_7_ext_R0_data : 8'h0),
    .io_bIn      (_pes_6_0_io_bOut),
    .io_aOut     (_pes_7_0_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_0_io_acc)
  );
  SystolicPE pes_7_1 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_1_io_clearAcc_T),
    .io_aIn      (_pes_7_0_io_aOut),
    .io_bIn      (_pes_6_1_io_bOut),
    .io_aOut     (_pes_7_1_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_1_io_acc)
  );
  SystolicPE pes_7_2 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_2_io_clearAcc_T),
    .io_aIn      (_pes_7_1_io_aOut),
    .io_bIn      (_pes_6_2_io_bOut),
    .io_aOut     (_pes_7_2_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_2_io_acc)
  );
  SystolicPE pes_7_3 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_3_io_clearAcc_T),
    .io_aIn      (_pes_7_2_io_aOut),
    .io_bIn      (_pes_6_3_io_bOut),
    .io_aOut     (_pes_7_3_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_3_io_acc)
  );
  SystolicPE pes_7_4 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_4_io_clearAcc_T),
    .io_aIn      (_pes_7_3_io_aOut),
    .io_bIn      (_pes_6_4_io_bOut),
    .io_aOut     (_pes_7_4_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_4_io_acc)
  );
  SystolicPE pes_7_5 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_5_io_clearAcc_T),
    .io_aIn      (_pes_7_4_io_aOut),
    .io_bIn      (_pes_6_5_io_bOut),
    .io_aOut     (_pes_7_5_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_5_io_acc)
  );
  SystolicPE pes_7_6 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (_pes_7_6_io_clearAcc_T),
    .io_aIn      (_pes_7_5_io_aOut),
    .io_bIn      (_pes_6_6_io_bOut),
    .io_aOut     (_pes_7_6_io_aOut),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_6_io_acc)
  );
  SystolicPE pes_7_7 (
    .clock       (clk),
    .reset       (rst),
    .io_en       (busy),
    .io_clearAcc (t == 8'hE),
    .io_aIn      (_pes_7_6_io_aOut),
    .io_bIn      (_pes_6_7_io_bOut),
    .io_aOut     (/* unused */),
    .io_bOut     (/* unused */),
    .io_acc      (_pes_7_7_io_acc)
  );
  assign s_axi_awready = awreadyReg;
  assign s_axi_wready = wreadyReg;
  assign s_axi_bresp = 2'h0;
  assign s_axi_bvalid = bvalidReg;
  assign s_axi_arready = arreadyReg;
  assign s_axi_rdata =
    raddrWord == 6'h1
      ? {28'h0, dmaDone, dmaBusy, done, busy}
      : raddrWord == 6'hA
          ? destAddr
          : raddrWord == 6'hB
              ? destStride
              : raddrWord == 6'h2
                  ? {24'h0, kLen}
                  : raddrWord == 6'h3
                      ? {30'h0, loadK}
                      : raddrWord == 6'h4
                          ? {29'h0, loadLane}
                          : raddrWord == 6'h7
                              ? {26'h0, resultIdx}
                              : _GEN ? casez_tmp_8 : raddrWord == 6'h9 ? 32'h1008 : 32'h0;
  assign s_axi_rresp = 2'h0;
  assign s_axi_rvalid = rvalidReg;
  assign mem_req_valid = memReqValid & dmaBusy & ~dmaSettle;
  assign mem_req_write = 1'h1;
  assign mem_req_addr = dmaAddr;
  assign mem_wline = casez_tmp;
endmodule

